// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuEZBLukiWDSTVzbIbiqD0hBcwytNrOT8',
    appId: '1:238385492464:web:f7b4b71723e6dbac0b6d35',
    messagingSenderId: '238385492464',
    projectId: 'kishen-portfolio-project',
    authDomain: 'kishen-portfolio-project.firebaseapp.com',
    storageBucket: 'kishen-portfolio-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBby_FS6Pw7CFaJWi8Cgznh5BEP6veH61c',
    appId: '1:238385492464:android:5e11cfc75bc31b2b0b6d35',
    messagingSenderId: '238385492464',
    projectId: 'kishen-portfolio-project',
    storageBucket: 'kishen-portfolio-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Y-3uLxIHDfIN_mJX4WjHAK7ZSBr28TE',
    appId: '1:238385492464:ios:6fcb89c6a48f4b560b6d35',
    messagingSenderId: '238385492464',
    projectId: 'kishen-portfolio-project',
    storageBucket: 'kishen-portfolio-project.appspot.com',
    iosClientId: '238385492464-7uhekkmmos6ahbr9p60q6vve42r45bs7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Y-3uLxIHDfIN_mJX4WjHAK7ZSBr28TE',
    appId: '1:238385492464:ios:6fcb89c6a48f4b560b6d35',
    messagingSenderId: '238385492464',
    projectId: 'kishen-portfolio-project',
    storageBucket: 'kishen-portfolio-project.appspot.com',
    iosClientId: '238385492464-7uhekkmmos6ahbr9p60q6vve42r45bs7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPortfolio',
  );
}
